FORMAT: 1A
HOST: https://protected-gorge-44302.herokuapp.com

# rentSTHLM
Välkommen! På den här sidan hittar du API-dokumentationen för rentSTHLMs REST-API.

Följande requests opererar på olika resurser som finns på servern. Om inget annat
specificeras utförs operationerna på den användare som indikeras av den autentiseringstoken
som skickas med varje request.

# Group Logga in och skapa hyresgästsprofil

## 1. Logga in via facebook [/facebook/login]
## POST mot /facebook/login [POST]

+ Request (application/json)

    + Attributes
        + facebookAuthToken: `EAACEdEose0cBAIID5sKglHcm01UYAGWP0cHgDEcAxrbDg0oZAzZCZC1Tlhw62ZBkhqMO6imdMtcQJqDfAGc8bKl08Q1FrR0Vz7SgVWh9sMEqUkUow07a3Vk3LwdHBMZANCXeTTKrlQGz2jOuOQJwGFZAk8RnHGpd1nU6F36OGtxtqZC50m7gSfo` -
        En token för auktorisering mot Facebooks Graph API.
        
+ Response 200

    + Headers

        Content-Type: application/json; charset=UTF-8

    + Attributes
        + authToken: `fa7f28df-8e2f-4c6d-8a78-0c0893318075`
        
## 2. Skapa en hyresgästprofil [/users/profiles]
## POST mot /users/profiles [POST]

+ Request (application/json)

    + Headers
    
            X-AUTH-TOKEN: fa7f28df-8e2f-4c6d-8a78-0c0893318075

    + Attributes (TenantProfile)

+ Response 204

# Group Logga in och skapa hyresobjekt

## 1. Logga in via facebook [/facebook/login]
## POST mot /facebook/login [POST]

+ Request (application/json)

    + Attributes
        + facebookAuthToken: `EAACEdEose0cBAIID5sKglHcm01UYAGWP0cHgDEcAxrbDg0oZAzZCZC1Tlhw62ZBkhqMO6imdMtcQJqDfAGc8bKl08Q1FrR0Vz7SgVWh9sMEqUkUow07a3Vk3LwdHBMZANCXeTTKrlQGz2jOuOQJwGFZAk8RnHGpd1nU6F36OGtxtqZC50m7gSfo` -
        En token för auktorisering mot Facebooks Graph API.
        
+ Response 200

    + Headers

        Content-Type: application/json; charset=UTF-8

    + Attributes
        + authToken: `fa7f28df-8e2f-4c6d-8a78-0c0893318075`

## 2. Skapa ett hyresobjekt [/accommodation]
## POST mot /accommodation [POST]

+ Request (application/json)

    + Headers
    
            X-AUTH-TOKEN: fa7f28df-8e2f-4c6d-8a78-0c0893318075

    + Attributes (Accommodation)

+ Response 204

# Group Anmäl intresse för hyresgäster

## 1. Hämta hyresgäster [/users{?maxrent,maxdeposit}]
## GET mot /users [GET]

+ Request

    + Headers

        X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200

    + Headers

        Content-Type: application/json; charset=UTF-8

    + Attributes(array[Tenant])

## 2. Skicka valda hyresgäster [/users]
## POST mot /users [POST]

+ Request (application/json)

    + Headers

        X-AUTH-TOKEN: en valid autentiseringstoken
        Content-Type: application/json; charset=UTF-8

    + Attributes
        + userIds: 2 (array[number])

+ Response 204

# Group Hämta hyresobjekt vars hyresvärd visat intresse för en

## 1. Hämta intressenamälningar [/interests{?renterId}]
## GET mot /interests [GET]

+ Request

    + Headers

        X-AUTH-TOKEN: en valid autentiseringstoken

+ Response 200

    + Headers

        Content-Type: application/json; charset=UTF-8

    + Attributes(array[Interest])

## Data Structures

### FacebookUser
+ email: kalle@example.com
+ firstName: Kalle
+ lastName: Blomkvist
+ gender: male

### LocalUser (FacebookUser)
+ id: 2
+ images: bilder (array)


### TenantProfile
+ description: `Hej, jag heter Kalle och behöver någonstans att bo.`
+ maxRent: 5000 (number)
+ maxDeposit: 8000 (number)
+ rentalPeriod
    + start: `2017-05-01`
    + end: `2018-05-01`

### Tenant (LocalUser)
+ profile (TenantProfile)

### Renter (LocalUser)
+ accommodation (Accommodation)

### Accommodation
+ rent: 5000 (number)
+ size: 20 (number)
+ rooms: 1 (number)
+ deposit: 8000 (number)
+ address (Address)

### Address
+ streetName: Dymlingsgränd
+ streetNumber: 3 (number)
+ streetNumberLetter: A

### Interest
+ renter (Renter)
